[theme]

#primaryColor = "#03417a" dark blue
#primaryColor = "#e6eef2" rgb(230,238,242) light light blue 
#primaryColor = "#c6e0f0"  light_blue
primaryColor = "#6f8dd6" # bluelu



# main background color of the page
#backgroundColor = "#c6e0f0"  light light blue
backgroundColor = "#0e1017" # bllaack



#background for inside widgets and stuff, also textinput
#secondaryBackgroundColor = "#8791dd" #rgb(135,145,221) dark weak blue 
secondaryBackgroundColor = "#32323e" # blac grey

#color for text but not st commands
textColor = "#fcfbf5" #rgb(3, 65, 122) beige

# text not for commands
font = "sans serif" 